docs_dir: docs/book
site_dir: docs/html
nav:
    - Home: index.md
    - Introduction: intro.md
    - Adapters: adapter.md
site_name: zend-serializer
site_description: "Serialize and deserialize PHP structures to a variety of representations"
repo_url: 'https://github.com/zendframework/zend-serializer'
